hw3 Крылов Дмитрий М3331
itmo2019/task3 pull request #1
Opened 2019-03-11 19:27 UTC by nibydlo

2019-03-16 17:38 UTC, nibydlo commented
Написал в телеграмм, но и тут спрошу.
Очевидно, что и при добавлении и при удалении происходят скачки.
Хотя казалось бы высота должна изменяться линейно.
Соответственно вопрос, из-за чего это происходит и как это пофиксить?

2019-03-23 04:15 UTC, mokhov commented
Основная ошибка здесь в том, что здесь не надо использовать анимацию, т.к свойства внутри `animation` можно вопринимать как дополнительный (отдельный) способ задавать селекторы (и выстрелить себе в ногу)

2019-03-23 04:16 UTC, mokhov commented
>  Хотя казалось бы высота должна изменяться линейно.
Линейно меняется высота блока, но не высота его содержимого. Т.е это не совсем то же самое что пропорционально менять параметры блока. Из-за это происходят скачки.

2019-03-23 04:19 UTC, mokhov requested changes
Чтобы отдебажить анимацию достаточно «проиграть» её, т.е позадавать явно те параметры, которые меняются и посмотреть что будет. Сейчас анимация ужасная и в живой продакшн такое я бы не пустил

2019-03-23 04:19 UTC, mokhov commented on hw2.css
> +.main__white-block {
В названии элемента нет ответа на вопрос: что содержится в этом элементе? Т.е для какого содержимого он предназначен?

2019-03-23 04:19 UTC, mokhov commented on hw2.css
> +.left-column__btn-group button {
Это не по BEM

2019-03-23 11:43 UTC, nibydlo commented
-> Заменил анимацию на трансформы
-> Чтобы содержимое не влияло на внешний размер, доавил overflow: hidden
-> Поменял имена классов

2019-04-06 07:35 UTC, closed without merging