HW3: Ваксман Денис, M3339
itmo2019/task3 pull request #13
Opened 2019-03-16 20:52 UTC by DrDet

2019-03-25 17:50 UTC, trixartem requested changes
Анимация хорошая, но есть важные замечания

2019-03-25 17:50 UTC, trixartem commented on main.js
> +var deleteAction = document.getElementsByClassName("mail-box__delete")[0];
Почему не querySelector?

2019-03-25 17:50 UTC, trixartem commented on main.js
> +    function() {
Для красоты можно вынести в отдельную функцию

2019-03-25 17:50 UTC, trixartem commented on main.css
> +    animation: deleting 500ms ease-in forwards !important;
Лучше делать через transition, потому что иначе приходится в js дожидаться, когда анимация закончится. А можно, добавив класс, провести анимацию
forwards - по умолчанию значение

2019-03-25 17:50 UTC, trixartem commented on main.css
> +.messages-list__message-snippet * {
Лучше явно указывать элементы, к которым надо применить стили. Старайся не использовать *, потому что можно в будущем словить баги.

2019-03-25 17:50 UTC, trixartem commented on index.html
> +        <header class="content__header">
Это может быть просто header

2019-03-28 21:01 UTC, DrDet commented on main.css
> +    animation: deleting 500ms ease-in forwards !important;
Так все равно придется дожидаться перед удалением из html же. Не понимаю, как transition поможет

2019-03-28 21:12 UTC, DrDet commented on index.html
> +        <header class="content__header">
В смысле блок, а не элемент?

2019-03-30 19:55 UTC, DrDet commented
Внес основные правки.

2019-05-12 05:29 UTC, trixartem commented on index.html
> +        <header class="content__header">
Ну да

2019-05-12 05:30 UTC, closed without merging