Даминов Нодир М3339
itmo2019/task3 pull request #15
Opened 2019-03-16 20:56 UTC by DaminovN

2019-03-25 12:58 UTC, mokhov requested changes
Кажется здесь нет ещё общих правок, о которых говорили в задаче №2. Поэтому жду правок второй задачи

2019-03-25 13:01 UTC, mokhov requested changes

2019-03-25 13:01 UTC, mokhov commented on style.css
> +.ya-mail__content-top-bar *{
Это не по БЭМ

2019-03-30 17:42 UTC, DaminovN commented
Исправил ошибки

2019-04-06 07:41 UTC, mokhov commented
На удаление не вижу анимации

2019-04-06 07:42 UTC, mokhov requested changes
Есть что ещё исправить

2019-04-06 07:42 UTC, mokhov commented on style.css
> +ul{
Общие стили лучше до частных стилей писать

2019-04-06 07:42 UTC, mokhov commented on style.css
> +.page__ya-menu-logo img{
Это не по БЭМ

2019-04-06 07:42 UTC, mokhov commented on style.css
> +.ya-sidebar__nav-sidebar li:not(.nav-sidebar__compose-message){
В терминах БЭМ всё что внутри `not` будет модификатором элемента. Т.е по БЭМ нельзя использовать псевдоселектор `not`

2019-04-06 07:42 UTC, mokhov commented on style.css
> +.ya-mail__content-top-bar ul{
Это не по БЭМ

2019-04-06 07:42 UTC, mokhov commented on style.css
> +.ya-mail__select-all input{
И это

2019-04-10 18:18 UTC, DaminovN commented
@mokhov исправил и добавил анимацию

2019-04-21 19:48 UTC, closed without merging