add solution
itmo2019/task3 pull request #16
Opened 2019-03-16 20:56 UTC by RuzikHan

Кнопка "Написать" добавляет новое письмо.
Кнопка "Удалить" удаляет письмо, выбранное до этого чекбоксом.

2019-03-26 07:41 UTC, mokhov commented
![Яндекс почта 2019-03-26 10-40-29](https://user-images.githubusercontent.com/357689/54979214-a35c8280-4fb3-11e9-865a-511f120aa856.jpg)
Типографика отличается

2019-03-26 08:06 UTC, mokhov requested changes

2019-03-26 08:06 UTC, mokhov commented on src/images/ya-default.svg
> +<?xml version="1.0" encoding="UTF-8"?>
svg можно пожать инструментом svgo, тогда лишняя инфа выбросится https://github.com/svg/svgo

2019-03-26 08:06 UTC, mokhov commented on src/index.html
> +                <li><p class="my-article__article-text">Фронтендом я интересовался еще в школе. В 9
Зачем в названии элемента `article`?

2019-03-26 08:06 UTC, mokhov commented on src/index.html
> +        <a href="#" class="buttons-links">
Класс дословно переводится как «кнопки-ссылки». Но это одна кнопка

2019-03-26 08:06 UTC, mokhov commented on src/index.html
> +        <a href="#" class="buttons-links">
Увы тут нарушена вложенность БЭМ блоков элементов. Такое было бы допустимо, если бы `button-links` не добавлял никаких стилей, а только лишь логику поведения, но я вижу в CSS что это не так

2019-03-26 10:08 UTC, RuzikHan commented
Исправлено

2019-04-13 19:53 UTC, evgenymarkov approved these changes

2019-04-13 19:53 UTC, closed without merging