Устинов Александр, M3335
itmo2019/task3 pull request #17
Opened 2019-03-16 20:57 UTC by alexust27

2019-03-26 21:15 UTC, underoot requested changes
За что так бедного тигра сплющил?
![image](https://user-images.githubusercontent.com/2480721/55031583-f1a76b00-501f-11e9-8347-3cf18496c7fd.png)

Ссылки в подвале слишком прижаты к верху
![image](https://user-images.githubusercontent.com/2480721/55031619-02f07780-5020-11e9-87b4-a9942f652f26.png)

2019-03-26 21:15 UTC, underoot commented on css/main.css
> +#get-letter {
Зачем здесь эти пустые селекторы?

2019-03-26 21:15 UTC, underoot commented on js/actions.js
> +let oneLetter = '<label>\n' +
Можно создать [шаблон](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) и его использовать для создания нового письма. Таким образом мы сократим связь между JavaScript и разметкой  письма

2019-03-26 21:15 UTC, underoot commented on js/actions.js
> +    allLetters.insertBefore(newLetter, allLetters.childNodes[2]);
Вставку можно было бы организовать проще если разместить в DOM контейнер для списка писем

2019-03-26 21:15 UTC, underoot commented on js/actions.js
> +            while (!letter.classList.contains('main-block__letter')) {
А что если пройтись по списку писем, заглядываю внутрь каждого в поиске выбранного _checkbox_?

2019-03-26 21:15 UTC, underoot commented on js/actions.js
> +    setTimeout(removeClass, 600, newLetter, 'animation-insert');
Чтобы избавиться от зависимости от времени анимации можно подписаться на событие `animationend`

2019-03-26 21:15 UTC, underoot commented on css/main.css
> +#remove {
Зачем пустой селектор?

2019-03-30 21:45 UTC, alexust27 commented on css/main.css
> +#get-letter {
Удалил

2019-03-30 22:01 UTC, alexust27 commented on css/main.css
> +#remove {
Убрал

2019-03-30 22:01 UTC, alexust27 commented
Исправил

2019-04-05 15:02 UTC, underoot commented on js/actions.js
> +    newLetter.addEventListener("webkitAnimationEnd", function () {
А почему префикс `webkit`? Такое не заработает уже в других браузерах кроме тех, что построены на базе webkit или blink движков (Chrome, Safari)...

2019-04-05 15:53 UTC, alexust27 commented on js/actions.js
> +    newLetter.addEventListener("webkitAnimationEnd", function () {
https://www.w3schools.com/jsref/event_animationend.asp тут написано следует для Chrome, Safari использовать `webkit`, думал что другие браузеры не нужны :smile:

2019-04-06 05:39 UTC, underoot approved these changes

2019-04-06 05:40 UTC, closed without merging