Терещук Максим, М3335
itmo2019/task3 pull request #19
Opened 2019-03-16 20:58 UTC by teremax

Удалять - двойной клик по письму.

2019-03-22 13:04 UTC, rmbaad requested changes

2019-03-22 13:04 UTC, rmbaad commented on src/script.js
> +function receiveLetter() {
Получение письма тоже должно быть с анимацией

2019-03-22 13:04 UTC, rmbaad commented on src/style.css
> +    from {
Забавно это выглядит, но есть пара недостатков
1. Если писем много, удаляемое письмо "летит" под списком и его не видно.
2. После того как письмо улетает за предел экрана, будет увеличиваться размер окна и можно скроллить за ним.

2019-03-22 13:04 UTC, rmbaad commented on src/style.css
> +    font-weight: 550;
Это должен быть чей-то модификатор

2019-03-22 13:04 UTC, rmbaad commented on src/style.css
> +#check_article {
От id пора избавляться

2019-03-22 13:04 UTC, rmbaad commented on src/index.html
> +                    <input class="entry_field" placeholder="Поиск">
Многое не по БЭМ-методологии, надо поправить

2019-03-23 17:40 UTC, teremax commented
@rmbaad, замечания учтены

2019-03-25 16:37 UTC, rmbaad approved these changes

2019-03-25 16:37 UTC, rmbaad commented on src/script.js
> +let letterTemplate = '<input type="checkbox" class="letter__check">'
Для шаблонов очень неудобно использовать и поддерживать конкатенацию. Воспользуйся template string https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings или html template

2019-03-25 16:37 UTC, rmbaad commented on src/style.css
> +#menu__incoming {
Должно быть классом

2019-03-25 16:37 UTC, rmbaad commented on src/style.css
> +.will_be_removed {
Правильнее было бы что-то вроде `will-be-removed` или `letter_will-be-removed` т.к. это скорее модификатор письма

2019-03-25 16:38 UTC, rmbaad commented
Апрув, но поправь то что я написал в следующем задании

2019-03-25 16:39 UTC, closed without merging