Балашов Ярослав, M3335
itmo2019/task3 pull request #2
Opened 2019-03-15 20:37 UTC by BreakChir

2019-03-15 20:40 UTC, BreakChir commented
Поддерживаются взаимодействие с чекбоксами и кнопки "Получить сообщение", "Удалить", "Прочитано".

2019-03-25 07:30 UTC, mokhov requested changes
Не плохо, но есть что доработать.

Ещё пара замечаний:
1. Почему анимация такая медленная
2. Немного расхождения с дизайном
![Яндекс Почта 2019-03-25 10-29-17](https://user-images.githubusercontent.com/357689/54901887-ef8ec080-4ee8-11e9-9b03-28e67abd3141.jpg)

2019-03-25 07:30 UTC, mokhov commented on css/letter-box.css
> +    margin: 0 10px 10px 10px;
Тут можно так `margin: 0 10px 10px`

2019-03-25 07:30 UTC, mokhov commented on css/menu.css
> +.menu > div {
По БЭМ правильнее каждому пункту дать класс

2019-03-25 07:30 UTC, mokhov commented on css/nav.css
> +.main__nav > * {
В БЭМ такого нужно избегать

2019-03-25 07:30 UTC, mokhov commented on css/nav.css
> +.write-button:hover {
Сегодня `white`, завтра `read`. Сегодня `button`, завтра `link`

2019-03-25 07:30 UTC, mokhov commented on css/style.css
> +main {
Тоже не по БЭМ

2019-03-25 07:30 UTC, mokhov commented on index.html
> +    <div class="logo header__logo">
Элементы `header` должны быть вложены в элемент с классом `header`

2019-03-25 07:30 UTC, mokhov commented on index.html
> +            <li><a href="index.html">Отправленные</a></li>
У всех остальных элементов должен быть минимум класс `nav__list-li`

2019-03-25 07:30 UTC, mokhov commented on index.html
> +            <li><a href="index.html">Отправленные</a></li>
Хотя `list-li` – это масло масленое

2019-03-25 20:30 UTC, BreakChir commented
Исправил bem
Не должно нигде остаться тегов, только классы
Все сгруппировал по блокам.

По поводу дизайна:
![image](https://user-images.githubusercontent.com/32174747/54951668-492cd480-4f55-11e9-905c-1a50b9be5282.png)
Теперь можно нажать в области
И поиск нужного цвета (у меня он и раньше был такого) - пришлось явно прописать color,
а вот почему линии жирные я действительно не понимаю, я посмотрел и кажется ничего на них не влияет, попробовал на маке и на винде - все линии тонкие...

2019-04-06 07:36 UTC, closed without merging