Дроздов Глеб, М3335
itmo2019/task3 pull request #24
Opened 2019-03-16 21:01 UTC by DrozdikGleb

2019-03-25 15:39 UTC, rmbaad requested changes

2019-03-25 15:39 UTC, rmbaad commented on scripts/letter-worker.js
> +            el.style.height = isRemove ? (30 - shift) + 'px' : shift + 'px';
По заданию нельзя делать анимацию на JS, она должна быть на CSS

2019-03-25 15:39 UTC, rmbaad commented on scripts/letter-worker.js
> +function createMessage() {
Некрасиво так и неудобно. Лучше так https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings
Или через html template

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +.header__search-box {
Лучше вынести всё, что касается расположения в элемент, а всё что касается внешнего вида самого блока унести в .search-box, иначе когда ты вынесешь этот блок в другое место, он будет спозиционирован не так, как тебе нужно

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +    box-shadow: inset 0 0 0 1px rgba(217, 219, 222, 1);
Если нет прозрачности, подойдёт и просто rgb()

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +.header__ya-logo {
Та же ситуация, как и с search-box. Зачем этому элементу класс блока если он нигде не используется? 
Нужно так же разнести внешние отступы/позиционирование в элемент, а стили самого блока унести в блок

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +.button-aside-menu#button-add-message {
Не по БЭМу. Можно сделать модификатор по типу

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +.main-block__footer a {
Не по БЭМу, у всего должен быть свой класс

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +.header__ya-logo {
++ footer

2019-03-25 15:39 UTC, rmbaad commented on index.html
> +            <li class="top-bar__horizontal-nav-panel__item"><a class="top-bar__horizontal-nav-panel__link menu-link"
Не может быть элементов у элементов

2019-03-25 15:39 UTC, rmbaad commented on index.html
> +            <li class="top-bar__horizontal-nav-panel__item"><a class="top-bar__horizontal-nav-panel__link menu-link"
Зачем horizontal-nav-panel делать элементом top-bar?

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +.button-aside-menu {
Блок не должен в названии содержать ничего извне. Он не должен знать где он будет находиться, т.к. он может быть где угодно

2019-03-25 15:39 UTC, rmbaad commented on styles.css
> +.header_hamburger {
header-hamburger

2019-03-30 14:45 UTC, DrozdikGleb commented
@rmbaad Переделал анимацию на css, исправил ошибки с бэм и поменял конкатенацию на  string template

2019-04-01 09:08 UTC, rmbaad approved these changes

2019-04-01 09:08 UTC, closed without merging