Kokorin Ilya, M3339
itmo2019/task3 pull request #27
Opened 2019-03-16 22:59 UTC by KokorinIlya

2019-03-25 16:26 UTC, rmbaad requested changes
Необходимо поправить, но в целом неплохо

2019-03-25 16:26 UTC, rmbaad commented on src/style.css
> +.letter-box_element {
element — немного странное название для булевого модификатора. Может быть планировался элемент?

2019-03-25 16:26 UTC, rmbaad commented on src/style.css
> +.letter-box_element {
++ ниже есть такие же случаи

2019-03-25 16:26 UTC, rmbaad commented on src/style.css
> +.all-mails-chooser {
Скорее это по логике должен быть элемент чего-то

2019-03-25 16:26 UTC, rmbaad commented on src/style.css
> +.mail-menu__menu-options {
Не критично, просто на будущее, обычно если есть два имени чего-то (в данном случае клас са)различающиеся как здесь options/option это может быть ненаглядно, лучше использовать что-то вроде option-list/option

2019-03-25 16:26 UTC, rmbaad commented on src/script.js
> +    drawnLetter.style.top = -letterSize + 'px';
По правилам задания, анимация должна быть на css, а не на js. Используй css transition

2019-03-25 16:27 UTC, rmbaad requested changes

2019-03-25 16:27 UTC, rmbaad commented on src/script.js
> +        '<ul class="letter__line">\n' +
Использовать конкатенацию строк неудобно и сложно поддерживать. Воспользуйся template strings https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings или html template

2019-03-25 16:32 UTC, KokorinIlya commented on src/script.js
> +    drawnLetter.style.top = -letterSize + 'px';
Но ведь в условии сказано, что можно написать немного JS, если умеете

2019-03-25 20:50 UTC, rmbaad commented on src/script.js
> +    drawnLetter.style.top = -letterSize + 'px';
Да, но не для анимаций. Вот цитата из чата, возможно ты пропустил

> да, JS можно использовать исключительно для запуска анимации

> Уточнение по ДЗ№3. JS допускается использовать для:
– Вставки HTML/Удаления HTML кода нового письма в списке писем
– Запуска удаления на любом элементе списка, в идеале здесь хочется уже как в почте: нажал галочку -> выделил -> нажал кнопку удалить
В остальных случаях JS использовать нельзя, пока

Запуска анимации, т.е. например для навешивания класса, но не для самой анимации, она должна быть на CSS

2019-03-25 22:27 UTC, KokorinIlya commented
@rmbaad, переделал, можете посмотреть?

2019-03-26 09:19 UTC, rmbaad approved these changes

2019-03-26 09:20 UTC, closed without merging