Дугинец Никита Hw3
itmo2019/task3 pull request #3
Opened 2019-03-16 15:16 UTC by glcanvas

кнопка "Добавить новое письмо" -- добавляет новое письмо.
если нажать на письмо, то оно удалится

2019-03-26 19:38 UTC, underoot requested changes
1) В очень многих местах присутствуют элементы неправильной BEM-нотации: элемент элемента
2) Стоит сделать через `transition` анимацию
3) Анимацию следует сделать вертикальной и не только для удаления, но и на добавление нового сообщения

2019-03-26 19:38 UTC, underoot commented on index.html
> +        <div class="header__action-button__line_black"></div>
В BEM не бывает элементов элементов. Можно исправить это использовав
1) Миксин элемента одного блока к элементу другого блока
2) Вложить [элементы друг в друга](https://ru.bem.info/methodology/html/#вложенность-элементов)

2019-03-26 19:38 UTC, underoot commented on scripts/letter-generate.js
> +let createNewLetter = document.getElementById("add-new-letter");
Не очень удачное название для переменной. Тут ведь сущность, а не действие над ним

2019-03-26 19:38 UTC, underoot commented on scripts/letter-generate.js
> +    let element = createLetter(countLetter);
То есть если из списка писем 1, 2, 3 удалим второе, то при создании создадим с айдишником 3?

2019-03-26 19:38 UTC, underoot commented on scripts/letter-generate.js
> +    element.addEventListener('click', deleteMessage(countLetter));
А можно удаление письма [делегировать](https://learn.javascript.ru/event-delegation) контейнеру писем

2019-03-26 19:38 UTC, underoot commented on scripts/letter-generate.js
> +function dfs(item) {
Это здесь для чего?

2019-03-26 19:38 UTC, underoot commented on styles/animation.css
> +    animation-duration: 2s;
Не слишком долго?

2019-03-26 19:38 UTC, underoot commented on scripts/letter-generate.js
> +function createLetter(id) {
Можно создать [шаблон](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) и его использовать для создания нового письма. Таким образом мы сократим связь между JavaScript и разметкой  письма

2019-03-27 18:20 UTC, glcanvas commented on scripts/letter-generate.js
> +    let element = createLetter(countLetter);
почему? я же увеличиваю `countLetter`

2019-03-27 21:11 UTC, glcanvas commented on index.html
> +        <div class="header__action-button__line_black"></div>
ок, кажется здесь я разобрался...

2019-03-28 10:12 UTC, glcanvas commented
@underoot  поправил

2019-04-05 14:18 UTC, underoot commented on scripts/letter-generate.js
> +    let element = createLetter(countLetter);
Да, увидел

2019-04-05 14:27 UTC, underoot approved these changes

2019-04-05 14:27 UTC, closed without merging