Савон Юлия M3337
itmo2019/task3 pull request #31
Opened 2019-03-18 00:57 UTC by Tiloaria

2019-03-26 08:35 UTC, mokhov commented
Анимацию удаления вижу, анимацию добавления не вижу :(

2019-03-26 08:38 UTC, mokhov requested changes
Кажется есть непонимание методологии в целом, если да, то посмотри это видео https://www.youtube.com/watch?v=V7_yj7L55k4

2019-03-26 08:38 UTC, mokhov commented on Yandex_front.html
> +                    <div class="check_mark" id="check_mark3"></div>
Это всё же элементы, а не отдельные блоки

2019-03-26 08:38 UTC, mokhov commented on style.css
> +.header_Yandex {
Почему тут большая буква?

2019-03-26 08:38 UTC, mokhov commented on style.css
> +.search_rectangle {
Зачем тут модификатор `прямоугольник`?

2019-04-04 12:40 UTC, Tiloaria commented
@mokhov замечания к текущему дз исправлены. Так же перенесены замечания из предыдущего.

2019-04-13 19:56 UTC, evgenymarkov approved these changes

2019-04-13 19:56 UTC, closed without merging