Волков Александр М3337
itmo2019/task3 pull request #32
Opened 2019-03-18 21:16 UTC by AlexVolkow

2019-03-27 07:29 UTC, underoot requested changes

2019-03-27 07:29 UTC, underoot commented on js/letters.js
> +        .call(document.getElementsByClassName("ya-checkbox"), (elem) => elem.checked)
Все чекбоксы на странице — дорого. Можно сделать селектор от контейнера с письмами. Каждый узел в DOM (не только `Document`) имеет методы для поиска внутри себя

2019-03-27 07:29 UTC, underoot commented on js/letters.js
> +        .filter((elem) => elem.id.localeCompare("select-all") !== 0 )
Сравнение строк с учетом локали? Не слишком неподходяще?

2019-03-27 07:29 UTC, underoot commented on js/letters.js
> +    setTimeout(() => checked.forEach((elem) => mails.removeChild(elem)), 700)
Чтобы не зависеть от времени анимации можно подписаться на событие `animationend`

2019-03-27 07:29 UTC, underoot commented on js/letters.js
> +function setAnimation(elem, animation) {
Можно сделать через `transition` и тогда достаточно будет указать желаемое значение и просто подписаться на событие `transitionend`

2019-03-27 07:29 UTC, underoot commented on js/letters.js
> +    element.className = style;
Стиль, который становиться `className` — это очень неочевидно

2019-03-27 07:29 UTC, underoot commented on js/letters.js
> +    const oldCtx = ctx;
Ты ведь заводишь такой контекст только ради того, чтобы в функциях во всех работать с текущим создаваемым элементом? Если так, то лучше сделать проще через передачу аргумента

2019-03-28 19:16 UTC, AlexVolkow commented
Сильно переделал создание письма

2019-04-05 15:07 UTC, underoot commented on index.html
> +            <button class="ya-big-button" onclick="sendLetter()">Написать</button>
Инлайн-обработчики — это антипаттерн. Лучше написать и навесить в JS

2019-04-08 14:07 UTC, underoot approved these changes

2019-04-08 14:07 UTC, closed without merging