Волошин Никита, М3335
itmo2019/task3 pull request #33
Opened 2019-03-23 01:19 UTC by nikvoloshin

Я не знаю, как вам удобнее проверять css и js: каждый блок в своем файле или один большой файл, поэтому в папке public уже собранный код, а в blocks - все по отдельности

Немного поменял верстку по сравнению с прошлым заданием: сделал ее более резиновой и убрал некоторые необязательные украшательства, которые делал в прошлом задании, чтобы убрать из кода этот ад на чекбоксах

Новое сообщение добавляется на кнопку "Написать"
Удаление сообщений - выделить нужные чекбоксы и нажать "Удалить" (check all не работает)

2019-03-27 08:45 UTC, underoot requested changes

2019-03-27 08:45 UTC, underoot commented on blocks/new-letter-button/new-letter-button.js
> +(function() {
А зачем понадобилась самовызывающаяся функция?

2019-03-27 08:45 UTC, underoot commented on blocks/new-letter-button/new-letter-button.js
> +	function createLetterHtml(content) {
Можно создать [шаблон](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) и его использовать для создания нового письма. Таким образом мы сократим связь между JavaScript и разметкой  письма

2019-03-27 08:45 UTC, underoot commented on blocks/new-letter-button/new-letter-button.js
> +    function parseDate(date) {
ISO 8601 умеет в формат даты, который ты используешь в данных. А значит ты можешь использовать `new Date()` и использовать его методы для получения компонент. Также есть вариант использовать `new Intl.DateTimeFormat('ru', { day: 'numeric', month: 'short' })`.

2019-03-27 08:45 UTC, underoot commented on blocks/delete-letters-button/delete-letters-button.js
> +			letter.addEventListener("animationend", () => {
Для приличия следует добавлять обработчики до старта анимации (чтобы не случилось такого, что анимация закончилась до того как повесили обработчики). Хотя это и не тот случай, но все же стоит ввести это в привычку

2019-03-27 08:45 UTC, underoot commented on blocks/new-letter-button/new-letter-button.js
> +	}
Что-то не так с отступами в файле

2019-03-27 08:49 UTC, nikvoloshin commented on blocks/new-letter-button/new-letter-button.js
> +(function() {
На первом курсе нас так учили) Инкапсуляция и все такое
Но хорошо, исправлю

2019-03-27 08:53 UTC, nikvoloshin commented on blocks/new-letter-button/new-letter-button.js
> +	}
Странно, не знаю почему на гите так, в IDE все нормально
![image](https://user-images.githubusercontent.com/27579652/55062364-eb98a500-5086-11e9-85ee-8fa50e6fda13.png)

2019-03-27 09:48 UTC, nikvoloshin commented on blocks/new-letter-button/new-letter-button.js
> +    function parseDate(date) {
month: 'short' выводит немного не в том виде
Например `сент.` вместо `сен`
Нужно ли в этом случае менять или оставить как есть?

2019-04-05 14:54 UTC, underoot approved these changes

2019-04-05 14:54 UTC, closed without merging