Егор Галкин, M3335
itmo2019/task3 pull request #34
Opened 2019-03-23 11:55 UTC by egalkin

2019-03-26 08:41 UTC, mokhov commented
Анимацию добавления вижу, удаления не вижу

2019-03-26 08:44 UTC, mokhov requested changes
Кажется есть непонимание методологии в целом, если да, то посмотри это видео https://www.youtube.com/watch?v=V7_yj7L55k4

2019-03-26 08:44 UTC, mokhov commented on src/index.html
> +            <a href="index.html" class = "_simple-link-view">
Что за странный класс?

2019-03-26 08:44 UTC, mokhov commented on src/index.html
> +                                    <p class="mail__yandex-team-2 mail__yandex-team-2_view _message_view">Команда Яндекс.Почты</p>
Что означает здесь 2?

2019-03-26 08:44 UTC, mokhov commented on src/styles.css
> +.Rectangle {
Почему с большой буквы?

2019-03-26 08:44 UTC, mokhov commented on src/styles.css
> +.team-body-2_view {
Не очень понятен смысл этого модификатора

2019-03-26 08:44 UTC, mokhov commented on src/styles.css
> +.ivan-ivanov {
Кажется это плохое название блока, т.к не отвечает на вопрос «Что это за блок?»

2019-03-26 09:32 UTC, egalkin commented on src/index.html
> +            <a href="index.html" class = "_simple-link-view">
Sidebar?

2019-03-26 09:33 UTC, egalkin commented on src/styles.css
> +.Rectangle {
Это уже неиспользуемый класс, сейчас удалю, но вообще я изначально когда еще второе делал брал названия из классов из макета, но потом понял, что это плохая идея и переписал.

2019-03-26 09:36 UTC, egalkin commented on src/index.html
> +            <a href="index.html" class = "_simple-link-view">
Если это про _simple-link-view, то у меня как раз был вопрос, как можно задавать глобальные модификаторы? У меня _simple-link-view и _text-overflow используются для многих эелементов в разных блоках, их тогда надо везде по новому называть и создавать копировать правилиа?

2019-05-16 18:28 UTC, evgenymarkov approved these changes

2019-05-16 18:30 UTC, closed without merging