Халимов Руслан, М3335
itmo2019/task3 pull request #35
Opened 2019-03-23 13:39 UTC by RuslanKhalimov

2019-03-23 13:41 UTC, RuslanKhalimov commented
Добавление письма по кнопке "Написать"
Удаление писем по кнопке "Удалить", работает для писем с выделенным чекбоксом
Работает выделение всех чекбоксов

2019-03-25 20:25 UTC, rmbaad requested changes

2019-03-25 20:25 UTC, rmbaad commented on index.html
> +            <li class="menu-buttons__button"><a href="#" class="main_links">Входящие</a></li>
Написано так, что links это модификатор main, должно быть скорее menu-buttons__link

2019-03-25 20:25 UTC, rmbaad commented on index.html
> +            <div class="hidden-page">
Кажется что это должно быть letter_hidden

2019-03-25 20:25 UTC, rmbaad commented on index.html
> +                    <div class="letter__new-letter-flag letter_new-letter-flag-enabled"></div>
enabled скорее должен быть модификатором, а new-letter-flag элементом, т.е. letter__new-letter-flag_enabled

2019-03-25 20:25 UTC, rmbaad commented on index.html
> +                        <div class="letter__author_abbr">Я</div>
author-abbr т.к. это имя элемента

2019-03-25 20:25 UTC, rmbaad commented on js/script.js
> +function addNewLetter() {
При добавлении письма нет анимации, а по заданию должна быть

2019-03-25 20:25 UTC, rmbaad commented on js/script.js
> +        '                <input class="letter__checkbox" type="checkbox">\n' +
Конкатенацию строк сложно поддерживать и читать, лучше используй template strings https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings или html template

2019-03-25 20:25 UTC, rmbaad commented on js/script.js
> +        '                <div class="letter__new-letter-flag letter_new-letter-flag-enabled"></div>\n' +
enabled должен быть модификатором

2019-03-31 11:53 UTC, RuslanKhalimov commented on index.html
> +            <li class="menu-buttons__button"><a href="#" class="main_links">Входящие</a></li>
Мне кажется это и есть модификатор, который действует не только в блоке ```menu-buttons```. 
Применяется к элементам ```menu-buttons__button``` и ```content-header-menu__button```. Тогда правильнее сделать одинаковый модификатор для обоих элементов, но с соответствующими названиями? Или я вообще не прав и, это все таки элемент?

2019-04-01 10:46 UTC, rmbaad commented on index.html
> +            <li class="menu-buttons__button"><a href="#" class="main_links">Входящие</a></li>
Да. Модификатор должен относиться к блоку (или элементу). Если он отвечает за одно и то же, его можно либо скопировать, либо вынести его действие в отдельный блок и миксовать

2019-04-01 10:46 UTC, rmbaad approved these changes

2019-04-01 10:47 UTC, closed without merging