Макеев Петр, M3337
itmo2019/task3 pull request #37
Opened 2019-03-23 19:04 UTC by Good-Morning

(В.г. сюда и 4ое задание затесалось)

2019-03-26 08:45 UTC, mokhov commented
А как получить письмо?

2019-03-26 08:46 UTC, mokhov requested changes
Есть что исправить

2019-03-26 08:46 UTC, mokhov commented on index.html
> +                        <div class="unread-letter-header">
Это слишком сильная декомпозия на блоки, многие из них всё же должны быть элементами

2019-03-26 08:46 UTC, mokhov commented on styles.css
> +.horizontal-list > li {
Это не по БЭМ

2019-03-26 09:20 UTC, Good-Morning commented
> А как получить письмо?

В задании есть фраза:
> Триггером анимации может быть отдельная кнопка, или же вы можете написать немного JS, если сможете.
Я так понял, что не обязательно кнопку сделать, а, например, таймер (чтобы сразу удовлетворять и четвертому заданию) - каждую минуту приходит новое письмо. Минута, потому что фразу из четвертого задания
> Раз в рандомное время (от 10 миллисекунд до 10 минут, но не чаще чем один раз в пять минут) 
я понять до конца не смог и взял более-менее компромиссный вариант.

Назначил кнопку "Написать" на добавление письма. (Остальное пока не исправлял.)

2019-03-30 22:01 UTC, Good-Morning commented
Теперь должно соответствовать требованиям БЭМ.
Структурировал файлы (по *.css на каждый блок).

2019-05-16 17:22 UTC, closed without merging