Михайленко Кристина М3335
itmo2019/task3 pull request #38
Opened 2019-03-23 21:12 UTC by KristinaMihajlenko

2019-03-26 08:48 UTC, mokhov requested changes
Анимации – ок. БЭМ надо доделать

2019-03-26 08:48 UTC, mokhov commented on src/styles/left-panel.css
> +.folders > ul {
Это не по БЭМ

2019-04-13 19:54 UTC, evgenymarkov approved these changes

2019-04-13 19:54 UTC, evgenymarkov commented on src/index.html
> +<body class="body">
Ну ладно уж, на body и html классы навешивать не надо

2019-04-13 19:54 UTC, closed without merging