Кузьмин Иван M3337
itmo2019/task3 pull request #41
Opened 2019-04-06 16:15 UTC by kuzmin-ivan

2019-04-21 19:53 UTC, mokhov requested changes

2019-04-21 19:53 UTC, mokhov commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Лишнее

2019-04-21 19:53 UTC, mokhov commented on index.html
> +        <div class="stripe burger-menu__stripe">
Если тебе везде нужен класс `stripe` значит что-то не так

2019-04-21 19:53 UTC, mokhov commented on index.html
> +            <input class="mail-search__input" type="text" placeholder="Поиск" onfocus="placeholder = ''"
Идея с `onfocus` и `onblur` не плохая, но работать будет плохо с точки зрения UX, т.к по факту всё введённое будет затёрто

2019-04-21 19:53 UTC, mokhov commented on index.html
> +            <li class="menu-list-tabs__tab" onclick="location.href='#'">Отправленные</li>
Зачем здесь такое странное поведенеие с `onclick`?

2019-04-21 19:56 UTC, mokhov commented
Анимации добавления письма (как и самого письма) не вижу
![screencast 2019-04-21 22-55-00](https://user-images.githubusercontent.com/357689/56474861-93d43a80-6488-11e9-9cbb-42ad49792220.gif)

p.s Ещё обрати внимание где крестик у поля поиска

2019-04-23 18:21 UTC, kuzmin-ivan commented
Спасибо за ревью, исправил замечания, в следующий раз не буду добавлять ненужные файлы, насчет анимации, у меня она работает, как и правильно отображается крестик, а на гиф-картинке, мне кажется, решение не моё, вот как выглядит у меня
![mail](https://user-images.githubusercontent.com/32925602/56605864-b6dc2700-660d-11e9-91be-10dec2d15981.gif)

2019-05-03 12:01 UTC, closed without merging