Виктория Ерохина, M3335
itmo2019/task3 pull request #6
Opened 2019-03-16 18:02 UTC by erokhinav

Кнопка "Написать" - добавить новое сообщение в начало списка сообщений,
Кнопка "Удалить" - удалить сообщение из начала списка сообщений.

2019-03-26 19:53 UTC, underoot requested changes

2019-03-26 19:53 UTC, underoot commented on src/js/script.js
> +let newLetterString = '<li class="message new-message">' +
Можно создать [шаблон](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) и его использовать для создания нового письма. Таким образом мы сократим связь между JavaScript и разметкой  письма

2019-03-26 19:53 UTC, underoot commented on src/js/script.js
> +    console.log(newLetterNode.body.firstChild);
Отладку стоит убрать

2019-03-26 19:53 UTC, underoot commented on src/js/script.js
> +    let messages = document.getElementsByClassName("message");
А что если список писем пуст?

2019-03-26 19:53 UTC, underoot commented on src/js/script.js
> +    setTimeout( function() {
Чтобы не зависеть от скорости анимации можно повесить обработчик на событие [`animationend`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/animationend_event)

2019-03-26 19:53 UTC, underoot commented on src/index.html
> +						<span class="checkbox__custom"></span>
`__custom` не похоже на элемент блока, скорее на его модификатор. Ну или стоит подумать над названием

2019-03-28 11:04 UTC, erokhinav commented
Fixed.

2019-04-05 14:28 UTC, underoot approved these changes

2019-04-05 14:29 UTC, closed without merging