Хусаинов Анвер, M3339
itmo2019/task3 pull request #7
Opened 2019-03-16 19:23 UTC by AnverK

2019-03-16 22:32 UTC, AnverK commented
Удаление -- отметить письма для удаления чекбоксами и нажать "удалить"
Добавление -- нажать кнопку "Переслать". Нелогично, но вот так вот

2019-03-26 07:21 UTC, mokhov commented
Но анимации на добавление-то нет :(

2019-03-26 07:22 UTC, mokhov requested changes
БЭМ – ок
Анимации нужно делать на CSS

2019-03-26 07:37 UTC, mokhov commented
Если растягивать окно по горизонтали, то справа появляется пустое место, это тоже лучше поправить

2019-03-28 12:51 UTC, AnverK commented
Исправил.

2019-05-16 17:23 UTC, closed without merging