Сайфулин Владислав, M3337
itmo2019/task3 pull request #9
Opened 2019-03-16 19:45 UTC by Recognized

2019-03-26 07:24 UTC, mokhov commented
Стили не применяются при добавлении
![Яндекс Почта 2019-03-26 10-24-02](https://user-images.githubusercontent.com/357689/54978392-4bbd1780-4fb1-11e9-9c65-136161b7b427.jpg)

2019-03-26 07:24 UTC, mokhov commented
Удаление не работает

2019-03-26 07:30 UTC, mokhov requested changes

2019-03-26 07:30 UTC, mokhov commented on css/mail.css
> +    height: calc(100% - 28px);
Много раз уже говорилсь, что `calc` – это плохо

2019-03-26 07:30 UTC, mokhov commented on css/mail.css
> +.sidebar_logo_container {
Кажется здесь нарушена логика БЭМ. Я не понимаю что означает этот модификатор

2019-03-26 07:30 UTC, mokhov commented on css/mail.css
> +    font-size: 32px;
Можно объединить с предыдущим правилом

2019-03-26 07:30 UTC, mokhov commented on css/mail.css
> +    border: none;
`border: 0`

2019-03-26 07:30 UTC, mokhov commented on css/mail.css
> +    font-weight: bold;
Можно объединить с прошлым правилом

2019-03-26 07:30 UTC, mokhov commented on css/mail.css
> +.sidebar__menu-list > li {
Это не по БЭМ

2019-04-13 19:52 UTC, evgenymarkov approved these changes

2019-04-13 19:52 UTC, evgenymarkov commented on js/index.js
> +function debounce(func, wait, immediate) {
В будущем лучше не копировать такие функции, а использовать уже готовые реализации из библиотек

2019-04-13 19:52 UTC, evgenymarkov commented on js/index.js
> +function x(tag, style, builder) {
Давай функциям более осмысленные имена)

2019-04-13 19:52 UTC, closed without merging